import { Inter } from 'next/font/google'
import './globals.css'

import Navbar from '../components/navbar'
import TransitonProvider from '../components/transitionProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Asif Portfolio App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <TransitonProvider>{children}</TransitonProvider>
      </body>
    </html>
  )
}
